FriendLinkStatus = str
ALLOWED_FRIEND_LINK_STATUSES = {"pending", "healthy", "rejected"}
ALLOWED_SITE_NAV_OPEN_TARGETS = {"blank", "self"}
ALLOWED_SITE_NAV_VISIBILITIES = {"public", "hidden", "private"}
PUBLIC_FRIEND_LINK_PENDING_LIMIT = 100
PUBLIC_FRIEND_LINK_PENDING_DOMAIN_LIMIT = 5
PUBLIC_FRIEND_LINK_DUPLICATE_SCAN_LIMIT = 5000
